const express = require("express");
const cors = require("cors");
require("dotenv").config();
const connectToDB = require("./connection");
const { userRoute } = require("./routes/user.routes");
const { carRoute } = require("./routes/car.routes");
const { authMiddleware } = require("./middleware/auth.middleware");
const { bookingRoute } = require("./routes/carBooking.routes");
const { transactionRoute } = require("./routes/transaction.routes");
const app = express();
app.use(cors());
const port = process.env.PORT || 8080;
const db_url = process.env.DB_URL;
connectToDB(db_url);
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
app.use("/auth", userRoute);
app.use("/car", carRoute);
app.use("/booking", authMiddleware, bookingRoute);
app.use("/transaction", authMiddleware, transactionRoute);
app.listen(port, () => console.log(`listening on http://localhost:${port}`));
